[package]
name = "pageturtle_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.3.3"
pageturtle_core = { path = "../pageturtle_core" }
comrak = "0.18.0"
